version: '3.8'

services:
  claude-middleware:
    image: lfreea/claude-relay-service:middleware-latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
      - TARGET_URL=http://claude-relay:3001
      - PROXY_TIMEOUT=300
      - MIDDLEWARE_AUTH_ENABLED=${MIDDLEWARE_AUTH_ENABLED:-false}
      - MIDDLEWARE_API_KEYS=${MIDDLEWARE_API_KEYS:-}
      - MIDDLEWARE_API_KEY_PREFIX=${MIDDLEWARE_API_KEY_PREFIX:-cr_}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - claude-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - claude-network

volumes:
  redis_data:

networks:
  claude-network:
    external: true  # 使用现有网络，或设置为false创建新网络