version: '3.8'

services:
  claude-middleware:
    image: lfreea/claude-relay-service:middleware-latest
    ports:
      - "8080:8080"
    environment:
      - TARGET_URL=http://claude-relay:3001
      - REDIS_HOST=redis
      - GIN_MODE=production
      - MIDDLEWARE_AUTH_ENABLED=${MIDDLEWARE_AUTH_ENABLED:-false}
      - MIDDLEWARE_API_KEYS=${MIDDLEWARE_API_KEYS:-}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - claude-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - claude-network

volumes:
  redis_data:

networks:
  claude-network:
    external: true  # 使用现有网络，或设置为false创建新网络